name: pinput_example
version: 1.0.0+1
publish_to: "none"
description: "PinPut Example"

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pinput:
    path: ../
  smart_auth: ^3.2.0
  material_ui: ^1.5.0
  google_fonts: ^9.0.0
  cupertino_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.1.0

flutter:
  uses-material-design: true
